use anyhow::Result;
use std::{
    fs::File,
    io::Write,
    path::{Path, PathBuf},
};

use crate::{
    config::{OutputFormat, SnapshotOptions},
    manifest::Manifest,
    project::Project,
    walk::{collect_source_files, is_hidden},
};

/// Trait for rendering file content in different output formats
pub(crate) trait Renderer {
    fn begin_file(&self, out: &mut dyn Write, path: &Path, lines: usize) -> Result<()>;
    fn end_file(&self, out: &mut dyn Write) -> Result<()>;

    /// Renders the header section
    fn write_header(&self, out: &mut dyn Write) -> Result<()> {
        Ok(())
    }

    /// Renders metadata section for a package
    fn write_package_metadata(
        &self,
        out: &mut dyn Write,
        package: &crate::cargo_toml::Package,
    ) -> Result<()> {
        Ok(())
    }

    /// Renders metadata section for a workspace
    fn write_workspace_metadata(&self, out: &mut dyn Write, manifest: &Manifest) -> Result<()> {
        Ok(())
    }

    /// Renders dependencies list
    fn write_dependencies(&self, out: &mut dyn Write, dependencies: &[String]) -> Result<()> {
        Ok(())
    }
}

/// Renders output in Rust comment format
pub(crate) struct RustRenderer;

impl Renderer for RustRenderer {
    fn begin_file(&self, out: &mut dyn Write, path: &Path, lines: usize) -> Result<()> {
        writeln!(
            out,
            "\n// ----- {} ({} lines) -----\n",
            path.display(),
            lines
        )?;
        Ok(())
    }

    fn end_file(&self, _: &mut dyn Write) -> Result<()> {
        Ok(())
    }

    fn write_header(&self, out: &mut dyn Write) -> Result<()> {
        writeln!(out, "// ========================================")?;
        writeln!(out, "// CARGO SNAPSHOT")?;
        writeln!(out, "// Generated by cargo-snapshot")?;
        writeln!(out, "// ========================================\n")?;
        Ok(())
    }

    fn write_package_metadata(
        &self,
        out: &mut dyn Write,
        package: &crate::cargo_toml::Package,
    ) -> Result<()> {
        writeln!(out, "// name: {}", package.name)?;
        if let Some(version) = &package.version {
            writeln!(out, "// version: {version}")?;
        }
        if let Some(edition) = &package.edition {
            writeln!(out, "// edition: {edition}")?;
        }
        if let Some(license) = &package.license {
            writeln!(out, "// license: {license}")?;
        }
        if let Some(description) = &package.description {
            writeln!(out, "// description: {description}")?;
        }
        Ok(())
    }

    fn write_workspace_metadata(&self, out: &mut dyn Write, manifest: &Manifest) -> Result<()> {
        let workspace_name = manifest
            .path
            .parent()
            .and_then(|p| p.file_name())
            .map(|n| n.to_string_lossy())
            .unwrap_or_else(|| "workspace".into());

        writeln!(out, "// workspace: {workspace_name}")?;
        writeln!(out, "// type: workspace")?;

        if let Some(workspace) = &manifest.cargo_toml.workspace {
            if !workspace.members.is_empty() {
                writeln!(out, "// members: {}", workspace.members.join(", "))?;
            }
            if let Some(resolver) = &workspace.resolver {
                writeln!(out, "// resolver: {resolver}")?;
            }

            if let Some(package) = &workspace.package {
                if let Some(version) = &package.version {
                    writeln!(out, "// version: {version}")?;
                }
                if let Some(edition) = &package.edition {
                    writeln!(out, "// edition: {edition}")?;
                }
                if let Some(license) = &package.license {
                    writeln!(out, "// license: {license}")?;
                }
            }
        }
        Ok(())
    }

    fn write_dependencies(&self, out: &mut dyn Write, dependencies: &[String]) -> Result<()> {
        if !dependencies.is_empty() {
            writeln!(out, "// dependencies: {}", dependencies.join(", "))?;
        }
        Ok(())
    }
}

/// Renders output in Markdown format with code blocks
pub(crate) struct MarkdownRenderer;

impl Renderer for MarkdownRenderer {
    fn begin_file(&self, out: &mut dyn Write, path: &Path, _: usize) -> Result<()> {
        writeln!(out, "\n## `{}`\n\n```rust", path.display())?;
        Ok(())
    }

    fn end_file(&self, out: &mut dyn Write) -> Result<()> {
        writeln!(out, "```")?;
        Ok(())
    }

    fn write_header(&self, out: &mut dyn Write) -> Result<()> {
        writeln!(out, "# CARGO SNAPSHOT")?;
        writeln!(out, "*Generated by cargo-snapshot*\n")?;
        writeln!(out, "---\n")?;
        Ok(())
    }

    fn write_package_metadata(
        &self,
        out: &mut dyn Write,
        package: &crate::cargo_toml::Package,
    ) -> Result<()> {
        writeln!(out, "**Package:** `{}`", package.name)?;
        if let Some(version) = &package.version {
            writeln!(out, "- **Version:** `{version}`")?;
        }
        if let Some(edition) = &package.edition {
            writeln!(out, "- **Edition:** `{edition}`")?;
        }
        if let Some(license) = &package.license {
            writeln!(out, "- **License:** `{license}`")?;
        }
        if let Some(description) = &package.description {
            writeln!(out, "- **Description:** {description}")?;
        }
        Ok(())
    }

    fn write_workspace_metadata(&self, out: &mut dyn Write, manifest: &Manifest) -> Result<()> {
        let workspace_name = manifest
            .path
            .parent()
            .and_then(|p| p.file_name())
            .map(|n| n.to_string_lossy())
            .unwrap_or_else(|| "workspace".into());

        writeln!(out, "**Workspace:** `{}`", workspace_name)?;
        writeln!(out, "- **Type:** workspace")?;

        if let Some(workspace) = &manifest.cargo_toml.workspace {
            if !workspace.members.is_empty() {
                writeln!(out, "- **Members:** `{}`", workspace.members.join("`, `"))?;
            }
            if let Some(resolver) = &workspace.resolver {
                writeln!(out, "- **Resolver:** `{resolver}`")?;
            }

            if let Some(package) = &workspace.package {
                if let Some(version) = &package.version {
                    writeln!(out, "- **Version:** `{version}`")?;
                }
                if let Some(edition) = &package.edition {
                    writeln!(out, "- **Edition:** `{edition}`")?;
                }
                if let Some(license) = &package.license {
                    writeln!(out, "- **License:** `{license}`")?;
                }
            }
        }
        Ok(())
    }

    fn write_dependencies(&self, out: &mut dyn Write, dependencies: &[String]) -> Result<()> {
        if !dependencies.is_empty() {
            writeln!(out, "- **Dependencies:** `{}`", dependencies.join("`, `"))?;
        }
        Ok(())
    }
}

/// Main writer for generating snapshot output
pub(crate) struct SnapshotWriter {
    options: SnapshotOptions,
    renderer: Box<dyn Renderer>,
}

impl SnapshotWriter {
    pub(crate) fn new(options: SnapshotOptions) -> Self {
        let renderer: Box<dyn Renderer> = match options.format {
            OutputFormat::Rust => Box::new(RustRenderer),
            OutputFormat::Markdown => Box::new(MarkdownRenderer),
        };
        Self { options, renderer }
    }

    /// Writes the complete snapshot to the output path
    pub(crate) fn write(&self, project: &Project, output: &Path) -> Result<()> {
        let mut file = File::create(output)?;

        self.renderer.write_header(&mut file)?;
        self.write_metadata(&mut file, &project.manifest)?;
        self.write_sources(&mut file, project)?;

        Ok(())
    }

    /// Writes metadata section with package/workspace information using the renderer
    fn write_metadata<W: Write>(&self, output: &mut W, manifest: &Manifest) -> Result<()> {
        match self.options.format {
            OutputFormat::Rust => writeln!(output, "// --- Metadata ---")?,
            OutputFormat::Markdown => writeln!(output, "## Metadata\n")?,
        }

        if let Some(package) = &manifest.cargo_toml.package {
            self.renderer.write_package_metadata(output, package)?;
        } else if manifest.is_workspace() {
            self.renderer.write_workspace_metadata(output, manifest)?;
        }

        let dependencies = manifest.dependencies();
        if !dependencies.is_empty() {
            self.renderer.write_dependencies(output, &dependencies)?;
        }

        writeln!(output)?;
        Ok(())
    }

    /// Writes all source files based on project type
    fn write_sources<W: Write>(&self, output: &mut W, project: &Project) -> Result<()> {
        if project.is_workspace_root() {
            self.write_workspace_sources(output, project)?;
        } else {
            self.write_single_crate_structure(output, project)?;
            self.write_crate_sources(
                output,
                &project.manifest.crate_name(),
                project.root_dir.join("src"),
                &project.root_dir,
            )?;
        }
        Ok(())
    }

    /// Writes directory structure for a single crate
    fn write_single_crate_structure(
        &self,
        output: &mut impl Write,
        project: &Project,
    ) -> Result<()> {
        match self.options.format {
            OutputFormat::Rust => {
                writeln!(output, "// ========== PROJECT STRUCTURE ==========\n")?;
                writeln!(output, "// {}/", project.manifest.crate_name())?;
                writeln!(output, "// └── src/")?;
                self.print_directory_structure(output, &project.root_dir.join("src"), "//     ")?;
            }
            OutputFormat::Markdown => {
                writeln!(output, "## Project Structure\n")?;
                writeln!(output, "```")?;
                writeln!(output, "{}/", project.manifest.crate_name())?;
                writeln!(output, "└── src/")?;
                self.print_directory_structure_markdown(
                    output,
                    &project.root_dir.join("src"),
                    "    ",
                )?;
                writeln!(output, "```")?;
            }
        }
        writeln!(output)?;
        Ok(())
    }

    /// Prints directory structure for Markdown output (without comment prefixes)
    fn print_directory_structure_markdown(
        &self,
        output: &mut impl Write,
        dir: &Path,
        prefix: &str,
    ) -> Result<()> {
        let mut entries: Vec<_> = std::fs::read_dir(dir)?
            .filter_map(Result::ok)
            .filter(|e| {
                let path = e.path();
                let is_rs = path.extension().is_some_and(|ext| ext == "rs");
                let is_dir = path.is_dir();

                if !self.options.include_hidden && is_hidden(&path) {
                    return false;
                }

                is_rs || is_dir
            })
            .collect();

        entries.sort_by(|a, b| {
            let a_is_dir = a.path().is_dir();
            let b_is_dir = b.path().is_dir();
            match (a_is_dir, b_is_dir) {
                (true, false) => std::cmp::Ordering::Less,
                (false, true) => std::cmp::Ordering::Greater,
                _ => a.file_name().cmp(&b.file_name()),
            }
        });

        for (i, entry) in entries.iter().enumerate() {
            let is_last = i == entries.len() - 1;
            let connector = if is_last { "└── " } else { "├── " };
            let name = entry.file_name();
            let name_str = name.to_string_lossy();

            if entry.path().is_dir() {
                writeln!(output, "{prefix}{connector}{name_str}/")?;
                let new_prefix = if is_last {
                    format!("{prefix}    ")
                } else {
                    format!("{prefix}│   ")
                };
                self.print_directory_structure_markdown(output, &entry.path(), &new_prefix)?;
            } else {
                writeln!(output, "{prefix}{connector}{name_str}")?;
            }
        }
        Ok(())
    }

    /// Prints directory structure for Rust output (with comment prefixes)
    fn print_directory_structure(
        &self,
        output: &mut impl Write,
        dir: &Path,
        prefix: &str,
    ) -> Result<()> {
        let mut entries: Vec<_> = std::fs::read_dir(dir)?
            .filter_map(Result::ok)
            .filter(|e| {
                let path = e.path();
                let is_rs = path.extension().is_some_and(|ext| ext == "rs");
                let is_dir = path.is_dir();

                if !self.options.include_hidden && is_hidden(&path) {
                    return false;
                }

                is_rs || is_dir
            })
            .collect();

        entries.sort_by(|a, b| {
            let a_is_dir = a.path().is_dir();
            let b_is_dir = b.path().is_dir();
            match (a_is_dir, b_is_dir) {
                (true, false) => std::cmp::Ordering::Less,
                (false, true) => std::cmp::Ordering::Greater,
                _ => a.file_name().cmp(&b.file_name()),
            }
        });

        for (i, entry) in entries.iter().enumerate() {
            let is_last = i == entries.len() - 1;
            let connector = if is_last { "└── " } else { "├── " };
            let name = entry.file_name();
            let name_str = name.to_string_lossy();

            if entry.path().is_dir() {
                writeln!(output, "{prefix}{connector}{name_str}/")?;
                let new_prefix = if is_last {
                    format!("{prefix}    ")
                } else {
                    format!("{prefix}│   ")
                };
                self.print_directory_structure(output, &entry.path(), &new_prefix)?;
            } else {
                writeln!(output, "{prefix}{connector}{name_str}")?;
            }
        }
        Ok(())
    }

    /// Writes all sources for a workspace project
    fn write_workspace_sources(&self, output: &mut impl Write, project: &Project) -> Result<()> {
        match self.options.format {
            OutputFormat::Rust => {
                writeln!(
                    output,
                    "// ========== WORKSPACE: {} ==========\n",
                    project.workspace_name(),
                )?;
            }
            OutputFormat::Markdown => {
                writeln!(output, "# Workspace: {}\n", project.workspace_name(),)?;
            }
        }

        self.write_project_structure(output, project)?;

        for member in &project.members {
            self.write_crate_sources(output, &member.name, member.src_dir(), &project.root_dir)?;
        }

        Ok(())
    }

    /// Writes the project structure tree
    fn write_project_structure(&self, output: &mut impl Write, project: &Project) -> Result<()> {
        match self.options.format {
            OutputFormat::Rust => {
                writeln!(output, "// ========== PROJECT STRUCTURE ==========\n")?;
                let root_name = project.root_dir.file_name().unwrap_or_default();
                writeln!(output, "// {}", root_name.to_string_lossy())?;
                for member in &project.members {
                    let relative = member
                        .absolute_path
                        .strip_prefix(&project.root_dir)
                        .unwrap_or(&member.absolute_path);
                    writeln!(output, "// ├── {}/", relative.display())?;
                    self.print_directory_structure(output, &member.src_dir(), "// │   ")?;
                }
            }
            OutputFormat::Markdown => {
                writeln!(output, "## Project Structure\n")?;
                writeln!(output, "```")?;
                let root_name = project.root_dir.file_name().unwrap_or_default();
                writeln!(output, "{}", root_name.to_string_lossy())?;
                for member in &project.members {
                    let relative = member
                        .absolute_path
                        .strip_prefix(&project.root_dir)
                        .unwrap_or(&member.absolute_path);
                    writeln!(output, "├── {}/", relative.display())?;
                    self.print_directory_structure_markdown(output, &member.src_dir(), "│   ")?;
                }
                writeln!(output, "```\n")?;
            }
        }
        writeln!(output)?;
        Ok(())
    }

    /// Writes all source files for a single crate
    fn write_crate_sources(
        &self,
        output: &mut impl Write,
        crate_name: &str,
        src_dir: PathBuf,
        root_dir: &Path,
    ) -> Result<()> {
        match self.options.format {
            OutputFormat::Rust => {
                writeln!(output, "// ========== CRATE: {crate_name} ==========\n")?;
            }
            OutputFormat::Markdown => {
                writeln!(output, "## Crate: {crate_name}\n")?;
            }
        }

        let files = collect_source_files(&src_dir, &self.options)?;

        for path in files {
            self.write_file(output, root_dir, &path)?;
        }
        Ok(())
    }

    /// Writes a single file with its content to the output
    fn write_file(&self, output: &mut impl Write, root_dir: &Path, file_path: &Path) -> Result<()> {
        let content = std::fs::read_to_string(file_path)?;
        let relative = file_path.strip_prefix(root_dir).unwrap_or(file_path);
        let normalized_path = relative.to_str().unwrap_or("").replace('\\', "/");
        let line_count = content.lines().count();

        // Use the existing renderer stored in SnapshotWriter
        self.renderer
            .begin_file(output, Path::new(&normalized_path), line_count)?;
        output.write_all(content.as_bytes())?;
        self.renderer.end_file(output)?;
        Ok(())
    }
}
