use std::io::Write;
use std::path::Path;

use anyhow::Result;

use crate::{cargo_toml::Package, manifest::Manifest};

use super::RendererImpl;

pub(crate) struct MarkdownRenderer;

impl RendererImpl for MarkdownRenderer {
    fn line_prefix(&self) -> &str {
        "" // В Markdown не нужен префикс для комментариев
    }

    fn begin_file<W: Write>(&self, out: &mut W, path: &Path, _lines: usize) -> Result<()> {
        writeln!(out, "\n## `{}`\n\n```rust", path.display())?;
        Ok(())
    }

    fn end_file<W: Write>(&self, out: &mut W) -> Result<()> {
        writeln!(out, "```")?;
        Ok(())
    }

    fn write_header<W: Write>(&self, out: &mut W) -> Result<()> {
        writeln!(out, "# CARGO SNAPSHOT")?;
        writeln!(out, "*Generated by cargo-snapshot*\n")?;
        writeln!(out, "---\n")?;
        Ok(())
    }

    fn write_package_metadata<W: Write>(&self, out: &mut W, package: &Package) -> Result<()> {
        writeln!(out, "**Package:** `{}`", package.name)?;

        if let Some(version) = &package.version {
            writeln!(out, "- **Version:** `{version}`")?;
        }
        if let Some(edition) = &package.edition {
            writeln!(out, "- **Edition:** `{edition}`")?;
        }
        if let Some(license) = &package.license {
            writeln!(out, "- **License:** `{license}`")?;
        }
        if let Some(description) = &package.description {
            writeln!(out, "- **Description:** {description}")?;
        }
        Ok(())
    }

    fn write_workspace_metadata<W: Write>(&self, out: &mut W, manifest: &Manifest) -> Result<()> {
        let workspace_name = manifest
            .path
            .parent()
            .and_then(|p| p.file_name())
            .map(|n| n.to_string_lossy())
            .unwrap_or_else(|| "workspace".into());

        writeln!(out, "**Workspace:** `{}`", workspace_name)?;
        writeln!(out, "- **Type:** workspace")?;

        if let Some(workspace) = &manifest.cargo_toml.workspace {
            if !workspace.members.is_empty() {
                writeln!(out, "- **Members:** `{}`", workspace.members.join("`, `"))?;
            }
            if let Some(resolver) = &workspace.resolver {
                writeln!(out, "- **Resolver:** `{resolver}`")?;
            }

            if let Some(package) = &workspace.package {
                if let Some(version) = &package.version {
                    writeln!(out, "- **Version:** `{version}`")?;
                }
                if let Some(edition) = &package.edition {
                    writeln!(out, "- **Edition:** `{edition}`")?;
                }
                if let Some(license) = &package.license {
                    writeln!(out, "- **License:** `{license}`")?;
                }
            }
        }
        Ok(())
    }

    fn write_dependencies<W: Write>(&self, out: &mut W, dependencies: &[String]) -> Result<()> {
        if !dependencies.is_empty() {
            writeln!(out, "- **Dependencies:** `{}`", dependencies.join("`, `"))?;
        }
        Ok(())
    }
}
