use std::io::Write;
use std::path::Path;

use anyhow::Result;

use crate::{manifest::Manifest, renderer::Renderer};

/// Renders output in Markdown format with code blocks
pub(crate) struct MarkdownRenderer;

impl Renderer for MarkdownRenderer {
    fn begin_file(&self, out: &mut dyn Write, path: &Path, _: usize) -> Result<()> {
        writeln!(out, "\n## `{}`\n\n```rust", path.display())?;
        Ok(())
    }

    fn end_file(&self, out: &mut dyn Write) -> Result<()> {
        writeln!(out, "```")?;
        Ok(())
    }

    fn write_header(&self, out: &mut dyn Write) -> Result<()> {
        writeln!(out, "# CARGO SNAPSHOT")?;
        writeln!(out, "*Generated by cargo-snapshot*\n")?;
        writeln!(out, "---\n")?;
        Ok(())
    }

    fn write_metadata(&self, out: &mut dyn Write) -> Result<()> {
        writeln!(out, "## Metadata\n")?;
        Ok(())
    }

    fn write_package_metadata(
        &self,
        out: &mut dyn Write,
        package: &crate::cargo_toml::Package,
    ) -> Result<()> {
        writeln!(out, "**Package:** `{}`", package.name)?;
        if let Some(version) = &package.version {
            writeln!(out, "- **Version:** `{version}`")?;
        }
        if let Some(edition) = &package.edition {
            writeln!(out, "- **Edition:** `{edition}`")?;
        }
        if let Some(license) = &package.license {
            writeln!(out, "- **License:** `{license}`")?;
        }
        if let Some(description) = &package.description {
            writeln!(out, "- **Description:** {description}")?;
        }
        Ok(())
    }

    fn write_workspace_metadata(&self, out: &mut dyn Write, manifest: &Manifest) -> Result<()> {
        let workspace_name = manifest
            .path
            .parent()
            .and_then(|p| p.file_name())
            .map(|n| n.to_string_lossy())
            .unwrap_or_else(|| "workspace".into());

        writeln!(out, "**Workspace:** `{workspace_name}`")?;
        writeln!(out, "- **Type:** workspace")?;

        if let Some(workspace) = &manifest.cargo_toml.workspace {
            if !workspace.members.is_empty() {
                writeln!(out, "- **Members:** `{}`", workspace.members.join("`, `"))?;
            }
            if let Some(resolver) = &workspace.resolver {
                writeln!(out, "- **Resolver:** `{resolver}`")?;
            }

            if let Some(package) = &workspace.package {
                if let Some(version) = &package.version {
                    writeln!(out, "- **Version:** `{version}`")?;
                }
                if let Some(edition) = &package.edition {
                    writeln!(out, "- **Edition:** `{edition}`")?;
                }
                if let Some(license) = &package.license {
                    writeln!(out, "- **License:** `{license}`")?;
                }
            }
        }
        Ok(())
    }

    fn write_dependencies(&self, out: &mut dyn Write, dependencies: &[String]) -> Result<()> {
        if !dependencies.is_empty() {
            writeln!(out, "- **Dependencies:** `{}`", dependencies.join("`, `"))?;
        }
        Ok(())
    }
}
