use crate::{
    SnapshotResult,
    renderer::{RenderStyle, Renderer},
};
use std::io::Write;

#[derive(Default)]
pub(crate) struct MarkdownRenderer;

impl Renderer for MarkdownRenderer {
    fn style(&self) -> RenderStyle {
        RenderStyle {
            line_prefix: "",
            metadata_key_prefix: "- ",
            file_open: |path, _content| format!("\n## `{path}`\n\n```rust"),
            file_close: "\n```",
            crate_heading: |name| format!("## Crate: {name}\n"),
            workspace_heading: |name| format!("# Workspace: {name}\n"),
            structure_begin: "## Project Structure\n\n```",
            structure_end: "```\n",
            structure_root: |name| format!("{name}/"),
            structure_member: |path| format!("├── {path}/"),
        }
    }

    fn render_header(&self, out: &mut dyn Write) -> SnapshotResult<()> {
        writeln!(out, "# CARGO SNAPSHOT")?;
        writeln!(out, "*Generated by cargo-snapshot*\n")?;
        writeln!(out, "---\n")?;
        Ok(())
    }
}
