use crate::{metadata::Metadata, renderer::metadata_formatter::MetadataFormatter};

use super::Renderer;
use crate::SnapshotResult;
use std::io::Write;

/// Renders output in Rust comment format
#[derive(Default)]
pub(crate) struct RustRenderer;

impl Renderer for RustRenderer {
    fn render_header(&self, out: &mut dyn Write) -> SnapshotResult<()> {
        writeln!(out, "// ========================================")?;
        writeln!(out, "// CARGO SNAPSHOT")?;
        writeln!(out, "// Generated by cargo-snapshot")?;
        writeln!(out, "// ========================================\n")?;
        Ok(())
    }

    fn render_metadata(&self, out: &mut dyn Write, metadata: &Metadata<'_>) -> SnapshotResult<()> {
        writeln!(out, "// --- Metadata ---")?;
        let mut formatter = MetadataFormatter::new(out, "// ");
        formatter.format(metadata)?;

        Ok(())
    }

    fn render_file(&self, out: &mut dyn Write, path: &str, content: &str) -> SnapshotResult<()> {
        let lines = content.lines().count();
        writeln!(out, "\n// ----- {path} ({lines} lines) -----\n")?;
        out.write_all(content.as_bytes())?;
        Ok(())
    }

    fn render_crate_heading(&self, out: &mut dyn Write, name: &str) -> SnapshotResult<()> {
        writeln!(out, "// ========== CRATE: {name} ==========\n")?;
        Ok(())
    }

    fn render_workspace_heading(&self, out: &mut dyn Write, name: &str) -> SnapshotResult<()> {
        writeln!(out, "// ========== WORKSPACE: {name} ==========\n")?;
        Ok(())
    }

    fn render_structure_begin(&self, out: &mut dyn Write) -> SnapshotResult<()> {
        writeln!(out, "// ========== PROJECT STRUCTURE ==========\n")?;
        Ok(())
    }

    fn render_structure_end(&self, out: &mut dyn Write) -> SnapshotResult<()> {
        writeln!(out)?;
        Ok(())
    }

    fn render_structure_root(&self, out: &mut dyn Write, name: &str) -> SnapshotResult<()> {
        writeln!(out, "// {name}/")?;
        Ok(())
    }

    fn render_structure_member(&self, out: &mut dyn Write, path: &str) -> SnapshotResult<()> {
        writeln!(out, "// ├── {path}/")?;
        Ok(())
    }

    fn tree_prefix(&self) -> &'static str {
        "// "
    }
}
