use std::io::Write;
use std::path::Path;

use anyhow::Result;

use crate::{cargo_toml::Package, manifest::Manifest};

use super::RendererImpl;

pub(crate) struct RustRenderer;

impl RendererImpl for RustRenderer {
    fn line_prefix(&self) -> &str {
        "// "
    }

    fn begin_file<W: Write>(&self, out: &mut W, path: &Path, lines: usize) -> Result<()> {
        writeln!(
            out,
            "\n// ----- {} ({} lines) -----\n",
            path.display(),
            lines
        )?;
        Ok(())
    }

    fn end_file<W: Write>(&self, _out: &mut W) -> Result<()> {
        Ok(())
    }

    fn write_header<W: Write>(&self, out: &mut W) -> Result<()> {
        writeln!(out, "// ========================================")?;
        writeln!(out, "// CARGO SNAPSHOT")?;
        writeln!(out, "// Generated by cargo-snapshot")?;
        writeln!(out, "// ========================================\n")?;
        Ok(())
    }

    fn write_package_metadata<W: Write>(&self, out: &mut W, package: &Package) -> Result<()> {
        let prefix = self.line_prefix();
        writeln!(out, "{prefix}name: {}", package.name)?;

        if let Some(version) = &package.version {
            writeln!(out, "{prefix}version: {version}")?;
        }
        if let Some(edition) = &package.edition {
            writeln!(out, "{prefix}edition: {edition}")?;
        }
        if let Some(license) = &package.license {
            writeln!(out, "{prefix}license: {license}")?;
        }
        if let Some(description) = &package.description {
            writeln!(out, "{prefix}description: {description}")?;
        }
        Ok(())
    }

    fn write_workspace_metadata<W: Write>(&self, out: &mut W, manifest: &Manifest) -> Result<()> {
        let prefix = self.line_prefix();
        let workspace_name = manifest
            .path
            .parent()
            .and_then(|p| p.file_name())
            .map(|n| n.to_string_lossy())
            .unwrap_or_else(|| "workspace".into());

        writeln!(out, "{prefix}workspace: {workspace_name}")?;
        writeln!(out, "{prefix}type: workspace")?;

        if let Some(workspace) = &manifest.cargo_toml.workspace {
            if !workspace.members.is_empty() {
                writeln!(out, "{prefix}members: {}", workspace.members.join(", "))?;
            }
            if let Some(resolver) = &workspace.resolver {
                writeln!(out, "{prefix}resolver: {resolver}")?;
            }

            if let Some(package) = &workspace.package {
                if let Some(version) = &package.version {
                    writeln!(out, "{prefix}version: {version}")?;
                }
                if let Some(edition) = &package.edition {
                    writeln!(out, "{prefix}edition: {edition}")?;
                }
                if let Some(license) = &package.license {
                    writeln!(out, "{prefix}license: {license}")?;
                }
            }
        }
        Ok(())
    }

    fn write_dependencies<W: Write>(&self, out: &mut W, dependencies: &[String]) -> Result<()> {
        if !dependencies.is_empty() {
            let prefix = self.line_prefix();
            writeln!(out, "{prefix}dependencies: {}", dependencies.join(", "))?;
        }
        Ok(())
    }
}
