use super::{Metadata, Renderer};
use anyhow::Result;
use std::io::Write;

/// Renders output in Rust comment format
#[derive(Default)]
pub(crate) struct RustRenderer;

impl RustRenderer {
    pub(crate) fn new() -> Self {
        Self
    }
}

impl Renderer for RustRenderer {
    fn render_header(&self, out: &mut dyn Write) -> Result<()> {
        writeln!(out, "// ========================================")?;
        writeln!(out, "// CARGO SNAPSHOT")?;
        writeln!(out, "// Generated by cargo-snapshot")?;
        writeln!(out, "// ========================================\n")?;
        Ok(())
    }

    fn render_metadata(&self, out: &mut dyn Write, metadata: &Metadata<'_>) -> Result<()> {
        writeln!(out, "// --- Metadata ---")?;

        if let Some(pkg) = metadata.package {
            writeln!(out, "// name: {}", pkg.name)?;
            if let Some(v) = &pkg.version {
                writeln!(out, "// version: {v}")?;
            }
            if let Some(e) = &pkg.edition {
                writeln!(out, "// edition: {e}")?;
            }
            if let Some(l) = &pkg.license {
                writeln!(out, "// license: {l}")?;
            }
            if let Some(d) = &pkg.description {
                writeln!(out, "// description: {d}")?;
            }
        }

        if let Some(ws) = metadata.workspace {
            if let Some(name) = &metadata.workspace_name {
                writeln!(out, "// workspace: {name}")?;
            }
            writeln!(out, "// type: workspace")?;

            if !ws.members.is_empty() {
                writeln!(out, "// members: {}", ws.members.join(", "))?;
            }
            if let Some(r) = &ws.resolver {
                writeln!(out, "// resolver: {r}")?;
            }
            if let Some(pkg) = &ws.package {
                if let Some(v) = &pkg.version {
                    writeln!(out, "// version: {v}")?;
                }
                if let Some(e) = &pkg.edition {
                    writeln!(out, "// edition: {e}")?;
                }
                if let Some(l) = &pkg.license {
                    writeln!(out, "// license: {l}")?;
                }
            }
        }

        if !metadata.dependencies.is_empty() {
            writeln!(out, "// dependencies: {}", metadata.dependencies.join(", "))?;
        }

        writeln!(out)?;
        Ok(())
    }

    fn render_file(&self, out: &mut dyn Write, path: &str, content: &str) -> Result<()> {
        let lines = content.lines().count();
        writeln!(out, "\n// ----- {path} ({lines} lines) -----\n")?;
        out.write_all(content.as_bytes())?;
        Ok(())
    }

    fn render_crate_heading(&self, out: &mut dyn Write, name: &str) -> Result<()> {
        writeln!(out, "// ========== CRATE: {name} ==========\n")?;
        Ok(())
    }

    fn render_workspace_heading(&self, out: &mut dyn Write, name: &str) -> Result<()> {
        writeln!(out, "// ========== WORKSPACE: {name} ==========\n")?;
        Ok(())
    }

    fn render_structure_begin(&self, out: &mut dyn Write) -> Result<()> {
        writeln!(out, "// ========== PROJECT STRUCTURE ==========\n")?;
        Ok(())
    }

    fn render_structure_end(&self, out: &mut dyn Write) -> Result<()> {
        writeln!(out)?;
        Ok(())
    }

    fn render_structure_root(&self, out: &mut dyn Write, name: &str) -> Result<()> {
        writeln!(out, "// {name}/")?;
        Ok(())
    }

    fn render_structure_member(&self, out: &mut dyn Write, path: &str) -> Result<()> {
        writeln!(out, "// ├── {path}/")?;
        Ok(())
    }

    fn tree_prefix(&self) -> &'static str {
        "// "
    }
}
